# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vwguxbA5JLZgkUWPUmXVJRfJwo2dMuKK
"""

name = input("Please enter your first name: ").title()

if name == "Fatih":
    print("Hello Fatih! The password is : Kule92")
else:
    print("Hello, Amina! See you later.")