# -*- coding: utf-8 -*-
"""Dairenin_yarıçapı.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qiHdw_TB_To1wykV8RYZtphYvOD1bI8Q
"""

#Dairenin yarıçapı ve alanını bulma

yarı_çap = int(input("Dairenin yarıçapını giriniz: "))
pi = 3.14

çevre = 2*pi*yarı_çap
alan = pi*(yarı_çap**2)

print("Dairenin çevre uzunluğu : ", çevre)

print("Dairenin alanı: ", alan)